name: thus_workspace
description: Workspace config for Thus chat monorepo.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.3

dependencies:
  meta: any

dev_dependencies:
  very_good_analysis: ^6.0.0
