name: thus_network
description: Networking (REST, WebSocket, SSE) layer for Thus apps using http.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  equatable: ^2.0.8
  http: ^1.2.1
  http_interceptor: ^2.0.0
  stream_transform: ^2.1.0
  thus_core:
    path: ../thus_core
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^6.0.0
  very_good_analysis: ^6.0.0
